- implementation/pom.xml
- pom.xml
* Remove org.jboss.spec.javax.servlet dependency in the implementation
(the Servlet is provided in the smallrye-metrics-rest-tck module)
* put Junit and AssertJ dependency in test scope
> Dependency cleanup

- implementation/pom.xml
- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusUnit.java
- implementation/src/test/java/io/smallrye/metrics/exporters/PrometheusExporterTest.java
- implementation/src/test/java/io/smallrye/metrics/exporters/PrometheusUnitScalingTest.java
* Fix time unit conversion in PrometheusUnit#scaleToBase where the time
unit of the value was not taken into account before scaling it to
seconds.
The value is now converted to nanoseconds before calling
ExporterUtil#convertNanosTo.
* Add PrometheusExporterTest#testUptimeGaugeUnitConversion that is
hightlighting the issue when monitoring the jvm.uptime gauge
* Fix bogus tests in PrometheusUnitScalingTest that were not asserting
* that the scaled values are in seconds.
Issue: https://github.com/smallrye/smallrye-metrics/issues/9
> [#9] Fix time unit conversion

- implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java
As the MetricRegistries is @ApplicationScoped, when it is destroyed, it
must clean up only the APPLICATION MetricRegistry.
Do not flag the `getBaseRegistry` and `getVendorRegistry` as
@ApplicationScope as they can be used outside of the application scope
(e.g. it's the responsibility of the container runtime to clean up its
vendor metrics).
JIRA: https://github.com/smallrye/smallrye-metrics/issues/12
> [#12] MetricRegistry cleanup

- implementation/src/main/java/io/smallrye/metrics/setup/JmxRegistrar.java
Instantiate the InputStream used to load vendor & base metrics in a
try-with-resources so that the InputStream is properly closed
afterwards.
> Close properties file resource stream

- implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java
Use the CDI extension name to uniquely identify the annotated types
This removes the warning I had when starting my application:
```
09:50:19,224 WARN  [org.jboss.weld.Bootstrap] (MSC service thread 1-1) WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used for class io.smallrye.metrics.interceptors.MeteredInterceptor is deprecated from CDI 1.1!
```
> Update calls to deprecated BeforeBeanDiscovery#addAnnotatedType

- implementation/pom.xml
- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusUnit.java
- implementation/src/test/java/io/smallrye/metrics/exporters/ExportersMetricScalingTest.java
Backport of https://github.com/smallrye/smallrye-metrics/pull/45 to 1.x
> [#40] fix unit scaling for Prometheus exporter, add test

- implementation/src/main/java/io/smallrye/metrics/JmxWorker.java
- implementation/src/main/java/io/smallrye/metrics/setup/JmxRegistrar.java
- implementation/src/test/java/io/smallrye/metrics/setup/JmxRegistrarTest.java
- implementation/src/test/resources/base-metrics.properties
This PR adds some more flexible JMX expressions with multiple wildcards as well as using them in tags. It fully backswards compatible with the existing "%s" syntax.
```
jboss_jdbc_active.mbean: jboss.as:subsystem=datasources,data-source=%s,statistics=pool/ActiveCount
jboss_jdbc_active.unit: connections
jboss_jdbc_active.description: Total number of connections in pool: %s
jboss_jdbc_active.multi: true
jboss_jdbc_active.type: gauge
jboss_jdbc_active.tags: data-source=%s
```
would result in prometheus metrics like this:
```
vendor:jboss_jdbc_active_connections{data-source="ExampleDS"} 0.0
```
or with multiple wildcards and syntax "%s1", "%s2", "%sN"...
```
undertow_listener_processingtime.mbean: jboss.as:subsystem=undertow,server=%s1,http-listener=%s2/processingTime …
```
> Support multiple wildcards and tags for JMX

- implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
One of the Thorntail tests fails with NPE [at this point](https://github.com/smallrye/smallrye-metrics/blob/1.1.3/implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java#L342). 
Using the concurrent map will detect earlier when a null value is inserted and it also makes sense to have both the metrics and the metadata maps concurrent
> Making the metadata map concurrent as well

- implementation/src/main/java/io/smallrye/metrics/JmxWorker.java
This relates to issue https://github.com/smallrye/smallrye-metrics/issues/131
The commit here changes a `log.info` to `log.debug` to reduce the messages that show up when the `JmxWorker` logs out a message about the replacements that it created for config entries.
> Reduce the log level in JmxWorker

- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
The spec says that there must be no unit appended to counters (https://github.com/eclipse/microprofile-metrics/blob/branch-1.1/spec/src/main/asciidoc/metrics_spec.adoc#325-counter-prometheus-text-format) 
This also fixes failure of relevant TCK test added through  https://github.com/eclipse/microprofile-metrics/commit/f11115affc724f6a94df8f890905e72b25bc8286 - this will be in spec 1.1.2 (not released yet)!
> [#53] don't append unit to counters

- implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
- implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java
Backport of https://github.com/smallrye/smallrye-metrics/pull/152 to metrics 2.0-1.1.x
> Properly parse Accept headers without q-value. Fixes #151

- implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
- implementation/src/test/java/io/smallrye/metrics/app/WeightedSnapshotTest.java
- implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java
Add a `smallrye.metrics.usePrefixForScope` configuration property
(`true` by default) that specifies whether the microprofile scope
(`base`, `vendor` or `application`) must be prefixed to the OpenMetrics
name or added to the metric's tags (with the key `microprofile_scope`).
This allows applications that were already providing metrics in
Prometheus/OpenMetrics to switch to smallrye-metrics to expose their
metrics while keeping the same names for metrics.
> Add configuration to put microprofile scope in OpenMetrics tag

- implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
- implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java
Add a `smallrye.metrics.usePrefixForScope` configuration property
(`true` by default) that specifies whether the microprofile scope
(`base`, `vendor` or `application`) must be prefixed to the OpenMetrics
name or added to the metric's tags (with the key `microprofile_scope`).
This allows applications that were already providing metrics in
Prometheus/OpenMetrics to switch to smallrye-metrics to expose their
metrics while keeping the same names for metrics.
Add OpenMetricsExporterTest#testMicroProfileScopeInTags
to test this configuration setting
> [MP-metrics 2.0.x] Add configuration to put microprofile scope in OpenMetrics tag

- implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java
backport of https://github.com/smallrye/smallrye-metrics/pull/165 to 2.1.x
> Properly handle CDI beans in the default package. Fixes #164

- implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
- implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java
#188
This is for master (targeting 2.3.0)
> Stop conflating names and keys in alreadyExportedNames map

- implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
- implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
Backport of https://github.com/smallrye/smallrye-metrics/pull/193 to 2.1.x for WildFly
> Prevent ConcurrentModificationException in MetricRegistryImpl

- README.adoc
we're not using semaphore for CI anymore
> Remove SemaphoreCI badge from the readme

- implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIBeanInfo.java
`Class.getPackage()` can return null, which can then cause a NPE, like it does here https://github.com/quarkusio/quarkus/pull/11656#issuecomment-681926931.
> Fix potential NPE in getPackageName

- api/pom.xml
- implementation/pom.xml
- pom.xml
It's empty for now, but we have a similar (although not empty) module with 2.4.x, so better include it with 3.0 as well, in the future we might move some stuff there
> API module

- implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java
- implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
Modify MetricsMetadata.registerMetrics to return list of MetricIDs registered
Modify MetricCdiInjectionExtension to store MetricID list in ivar
Add observer method for BeforeShutdown that filters application registry, removing any metrics in MetricID list
> Update smallrye-metrics to clean up application registry on undeploy

- implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
Modify MetricsRegistryImpl.removeMatching so that identifies all matching
metrics, and then removes them once iteration has completed.
This is related to https://github.com/smallrye/smallrye-metrics/issues/36
> [WFLY-12970] Do not call remove while iterating

- implementation/src/main/java/io/smallrye/metrics/MemberToMetricMappings.java
fixes https://github.com/smallrye/smallrye-metrics/issues/444
> Improve MemberToMetricMappings a bit, add javadoc

- implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
- implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java
> Requests without an Accept header are not accepted

- api/pom.xml
- coverage/pom.xml
- implementation/pom.xml
- implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIAnnotationInfo.java
- implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/MetricResolver.java
- implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
- pom.xml
- release/pom.xml
- Use 5.0.0-SNAPSHOT for version
- Use MP Metrics 5.0.0-SNAPSHOT, see https://github.com/eclipse/microprofile-metrics/pull/664 
- - Remove references to removed metrics
- Fix Missing ThreadLocal usage for Gauges (ThreadLocal used w/ MeterFilter)
- Fix MetricsMetadata appending scope tag (not needed as its appended to meter on micrometer level w/ filter)
- quantiles/percentiles (to be configurable) to Timer and Histogram (DistributionSummary) 
- Fix including mp.metrics.appName into  MetricID passed to MemberMetricMapping metric maps (probably remove this in the future and query/retrieve directly from metric/meter-registry??)
Changes Probably won't pass the SR build as we can't pull 5.0.0-SNAPSHOT from MP Metrics.
> Fixes and Misc changes to Micrometer branch

- implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
- implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
- Include mp.metrics.appName in `MetricID` when creating metric from @Timed, also for query by forwarding Gauge
- Register/(retrieve) from Global registry in Histogram, Gauge and Timer.
> Micrometer more fixes

- pom.xml
This PR addresses #506 by adding the Eclipse Transformer Maven plugin to provide artifacts that use the `jakarta` namespace as well as the regular artifacts that currently use `javax`.
> Issue #506: Use the Eclipse Transformer Plugin

- implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
- implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java
- implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
- implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
- implementation/src/main/java/io/smallrye/metrics/elementdesc/AnnotationInfo.java
- implementation/src/main/java/io/smallrye/metrics/elementdesc/RawAnnotationInfo.java
- implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIAnnotationInfo.java
- implementation/src/main/java/io/smallrye/metrics/exporters/Exporter.java
- implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java
- implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/SnapshotAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/GaugeRegistrationInterceptor.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
- implementation/src/main/java/io/smallrye/metrics/setup/MPPrometheusMeterRegistry.java
- implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
- implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
- implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/MetadataMismatchTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java
Related to: https://github.com/eclipse/microprofile-metrics/pull/712a
Depends on :
FIRST: https://github.com/smallrye/smallrye-metrics/pull/513
SECOND: https://github.com/smallrye/smallrye-metrics/pull/517
(Current PR contains the commits of above 2 )
Relevant commit is (or whatever the last commit is ):https://github.com/smallrye/smallrye-metrics/pull/521/commits/4fdf22ffea78713e8971b4d84e9d1d0d8ede5098
Implement getSnapShot() for `Histogram` and `Timer`
Add `SnapshotAdapter` which implements the new changes in MP Metrics 5.0
> Micrometer custom scopes + Gauge number change + Histo/Timer updates + Snapshot updates

- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
This PR forces the `base` scope to be created, which in turn adds the base JVM metrics.
> Force create the base registry

- implementation/src/main/java/io/smallrye/metrics/micrometer/MicrometerBackends.java
Config property prefix should be mp.metrics. as opposed to microprofile.metrics., per the specification recommendation.
> Correct backend config property prefix

- .github/dependabot.yml
- .github/workflows/build.yml
- README.adoc
Similar to : 
https://github.com/smallrye/smallrye-metrics/commit/e40d844d6056597459fedacd7f917fc704e89ce3
Some of the changes were already made previously.
Skipped the publishing of TCK change.
> Remove Java 8 from build, MP Config no longer supports Java 8

- implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/SeMetricName.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
For the `micrometer` branch.
A few things:
- Make methods public to help with implementations that need to proxy the methods othe clsas.
- Directly instantiate SeMetricName in MetricProducer, instead of using CDI.
^Was initially intending to completely remove the `MetricNameFactory` and merge `SeMetricName` and the `MetricName` interface together as one (i.e. result in a `MetricName` **class** in the end, but noticed that there may have been intentions to provide support for an _external_ CDI strategies? (Worth dicussing) See :https://github.com/smallrye/smallrye-metrics/blob/main/implementation/src/main/java/io/smallrye/metrics/interceptors/MetricName.java#L27
- Not use Jboss logging to throw ISE in counted and timed interceptors.
^Need to finalize on a logging solution.
> Make certain classes more proxy-able

- implementation/src/main/java/io/smallrye/metrics/legacyapi/FunctionCounterAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
Used directly with the metric registry implementation.
This is not part of the MP Metrics specification.
Since it should be used _internally_ by runtimes/vendors,  I've only included the  `public <T> Counter counter(Metadata metadata, T obj, ToDoubleFunction<T> func, Tag... tags)` method signature. Can update to include others method signatures.
> Include support for a function counter for _internal_ use. 

- implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
The use of `memoryMXBean.getHeapMemoryUsage()::getUsed` causes `getUsed()` to be called on an old memory usage object. The effect here is that the 1st value scraped would be reported indefinitely.
Using `() -> memoryMXBean.getHeapMemoryUsage().getUsed()` gets a new memory usage object from the MBean each time.
> Fix incorrectly reported heap metrics

- implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
Instead of a Micrometer Meter Binder, mirror it, but register directly to the MP Metric Registry.
fixes #566 
Not sure why formatter plugin has changed.
> Register base metrics to MP Metric Registry

- implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
- boolean for presence of AppNameResolver, use before addNameToApplicationMap to reduce MetricDescriptor to MetricID conversion
- create HashMap in combineApplicationTagsWithMPConfigAppNameTag after MP Config property  null check
- removed isSorted parameter from above mentioned method
- Included ctor for HistogramAdapter with MeterRegistry param for consistency
other:
- Cleaned up commented code + sys out
- Removed useless object substitute in log statement in SharedMetricRegistries
fixes #562
> Address code improvements from issue:

- implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/SnapshotAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/DefaulBucketConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/DefaultBucketConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/HistogramBucketConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/HistogramBucketMaxConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/HistogramBucketMinConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/MetricPercentileConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/MetricsConfigurationManager.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/PropertyArrayConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/PropertyBooleanConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/PropertyConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/PropertySingleValueConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMaxConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMinConfiguration.java
- pom.xml
Context the new MP Config properties for metrics v5.1 follow the following syntax:
```
<property>=<metric_name>=value[,value2,value3];<metric_name2>=value[,value2,value3]
```
^^ That is to say property is a semi-colon separated _values_ that define the configuration for a specific metric name.
`MericsConfigurationManger` has `getxxx()` which returns an respective sub-class of `PropertyConfiguration` .
For example `getPercentilesConfiguration(...)` returns `MetricPercentileConfiguration`.
This is called as appropriate from the `HistogramAdapter` or `TimerAdapter` during registration as it needs this info to customize the metric.
During the `getxxx()`, it checks if `MericsConfigurationManger` contains an existing _collection of configuration objects_ for the app name that is passed in in …
> Support Mp Metrics 5.1 MP Config properties for Histogram and Timer metrics

- implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/HistogramBucketMaxConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/HistogramBucketMinConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMaxConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMinConfiguration.java
- Include "bucket" for generating the suffixed metric names for filtering from micrometer. (For when using the query params to filter out a specific scope and metric name)
- Null checks for Histogram/Timer max/min configuration.
> Additional fixes for 5.1.0

- implementation/pom.xml
- implementation/src/main/java/io/smallrye/metrics/MPPrometheusConfig.java
- implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
- implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
- implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
- implementation/src/main/java/io/smallrye/metrics/legacyapi/MetricDescriptor.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/MetricPercentileConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/MetricsConfigurationManager.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/PropertyConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMaxConfiguration.java
- implementation/src/main/java/io/smallrye/metrics/setup/config/TimerBucketMinConfiguration.java
- implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java
- implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
- implementation/src/test/java/io/smallrye/metrics/configuration/DefaultBucketTest.java
- implementation/src/test/java/io/smallrye/metrics/configuration/HistogramConfigurationTest.java
- implementation/src/test/java/io/smallrye/metrics/configuration/PercentileConfigurationTest.java
- implementation/src/test/java/io/smallrye/metrics/configuration/TimerConfigurationTest.java
- implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/MetadataMismatchTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
- implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java
- pom.xml
- Update to Junit 5
- Write new junits for v51 metric config parsing Fixes:
- MetricPercentileConfiguration - no input
- Sort TimerBucketConfiguration values
- Default of millis instead of seconds for timer max/min config
> - Update to SmallRye Parent 40
