implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java

This was leading to a IllegalStateExcetion a few lines later when the response was again sent with state 200.

Added missing return statement to MetricsRequestHandler.

---

implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/PrometheusExporterTest.java

Fix Prometheuse snake case conversion to properly handled successive
uppercase characters.
Issue: https://github.com/smallrye/smallrye-metrics/issues/16

[#16] Prometheus snake case conversion

---

testsuite/rest-tck/pom.xml

Fix for issue https://github.com/smallrye/smallrye-metrics/issues/37

[#37] Make rest-tck run with JDK 9+

---

implementation/pom.xml
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusUnit.java
implementation/src/test/java/io/smallrye/metrics/exporters/ExportersMetricScalingTest.java

https://issues.jboss.org/browse/WFLY-11458
https://github.com/smallrye/smallrye-metrics/issues/40

[#40] fix unit scaling for Prometheus exporter, add test

---

implementation/src/main/java/io/smallrye/metrics/exporters/JsonExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/JsonExporterTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/PrometheusExporterTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeHistogram.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeMeter.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeSnapshot.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeTimer.java

This a demonstration and a partial fix for https://github.com/smallrye/smallrye-metrics/issues/51
If the feedback for this PR is good, I'll change the two other type casts and add corresponding tests.

improve type casts in the exporters

---

implementation/src/main/java/io/smallrye/metrics/interceptors/ConcurrentGaugeInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MeteredInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricsInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/TimedInterceptor.java

https://github.com/smallrye/smallrye-metrics/issues/90

Change interceptor methods from private to package private. Fixes #90

---

implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java

https://github.com/smallrye/smallrye-metrics/issues/93

Remove camelCase to snake_case conversion. Fixes #93

---

implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java

Issue: https://github.com/smallrye/smallrye-metrics/issues/38
TCK test to cover this: https://github.com/eclipse/microprofile-metrics/pull/314 
PR to master coming after relevant 2.0 changes are merged (they conflict with this a bit)

[#38] attach metadata to metrics generated by producer methods

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java

This will be useful if Quarkus guys decide to move the MP endpoints to some separate namespace. See https://github.com/smallrye/smallrye-metrics/issues/82

[DO NOT MERGE YET] (1.1.x) Allow passing the expected metrics context root. Fixes #82

---

implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java

https://github.com/smallrye/smallrye-metrics/issues/101

Making the metadata map concurrent as well. Fixes #101

---

implementation/src/main/java/io/smallrye/metrics/exporters/JsonExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/JsonExporterTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/PrometheusExporterTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeHistogram.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeMeter.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeSnapshot.java
implementation/src/test/java/io/smallrye/metrics/exporters/SomeTimer.java

https://github.com/smallrye/smallrye-metrics/issues/105

backport of PR 52 to 1.1.x

---

testsuite/common/src/main/resources/io/smallrye/metrics/base-metrics.properties

Fixes https://github.com/smallrye/smallrye-metrics/issues/110

Implement base metrics changes per 2.0 specification. Fixes #110

---

implementation/pom.xml
pom.xml
release/pom.xml
testsuite/api-tck/pom.xml
testsuite/common/pom.xml
testsuite/extra/pom.xml
testsuite/pom.xml
testsuite/rest-tck/pom.xml
testsuite/rest-tck/src/test/java/io/smallrye/metrics/tck/rest/ArchiveProcessor.java

Also updates to new implementation artifactId and version

Updates to latest parent and adds fixes for release process.

---

implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java

https://github.com/smallrye/smallrye-metrics/issues/123

Demote INFO messages about metric registration/removal. Fixes #123

---

pom.xml

2.0.0 should be the correct one to use

Change spec version from 2.0 to 2.0.0

---

implementation/src/main/java/io/smallrye/metrics/exporters/JsonExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/JsonExporterTest.java

https://github.com/smallrye/smallrye-metrics/issues/76

rewrite JsonExporter to use JSON-P

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricsInterceptor.java

see https://github.com/smallrye/smallrye-metrics/issues/148

Remove internal usage of Gauge<Object>. Fixes #148

---

implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java
implementation/src/main/resources/project.properties

https://github.com/smallrye/smallrye-metrics/issues/141

Log the implementation version at initialization

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java

Properly parse Accept headers without q value. Fixes #151

---

implementation/pom.xml
pom.xml
release/pom.xml
testsuite/api-tck/pom.xml
testsuite/common/pom.xml
testsuite/extra/pom.xml
testsuite/pom.xml
testsuite/rest-tck/pom.xml
testsuite/rest-tck/src/test/java/io/smallrye/metrics/tck/rest/ArchiveProcessor.java

Update to revised artifact/version scheme

---

implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java

This is a new API addition in MP Metrics 2.1

Make use of the new reusable(boolean) method to make code more readable

---

testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_ConcurrentGauge_Method_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Counter_ClassLevel_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Counter_Constructor_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Counter_Method_Reusable_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Counter_Method_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Gauge_Method_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Injection_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Meter_Method_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_ProducerField_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_ProducerMethod_Test.java
testsuite/extra/src/test/java/io/smallrye/metrics/test/initialization/Initialization_Timer_Method_Test.java

Get rid of org.wildfly.swarm package in tests

---

implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java

Prevent ConcurrentModificationException in MetricRegistryImpl

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/interceptors/ConcurrentGaugeInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MeteredInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricNameFactory.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricsInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/TimedInterceptor.java

Change private injections to package-private

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/interceptors/ConcurrentGaugeInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MeteredInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricNameFactory.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MetricsInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/TimedInterceptor.java

Backport to 2.3.x branch for Quarkus

Change private injections to package-private. Fixes #199

---

pom.xml

Update Metrics API and SmallRye Config

---

implementation/src/test/resources/base-metrics.properties

The remaining still relevant part of the now closed PR #31

Change gc.%s.time metric to gauge for TCKs

---

implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java

Fixes https://github.com/smallrye/smallrye-metrics/issues/224

Don't fail if MP Config implementation is not available

---

implementation/pom.xml
pom.xml
testsuite/api-tck/pom.xml
testsuite/common/pom.xml
testsuite/extra/pom.xml

Should be merged after updating to a MP Metrics API dependency that contains https://github.com/eclipse/microprofile-metrics/pull/500

Move to Jakarta dependencies

---

implementation/src/main/java/io/smallrye/metrics/ExtendedMetadata.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java

#234 
Yep, the `ExtendedMetadata` class is now extra ugly. I'm planning to clean it up and implement a builder later (for 2.4.0 perhaps)

Hacks needed to support Micrometer compatibility mode

---

implementation/src/main/java/io/smallrye/metrics/app/SimpleTimerImpl.java
implementation/src/main/java/io/smallrye/metrics/exporters/JsonExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/JsonExporterTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java
implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java
pom.xml

RC1 + SimpleTimer update

---

implementation/src/main/java/io/smallrye/metrics/ExtendedMetadata.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java

Fixes https://github.com/smallrye/smallrye-metrics/issues/234 
Already applied in 2.3.x

Port #234 to master

---

pom.xml

Update to SR Config to 1.6.0

---

implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java

Ability to drop all registries

---

implementation/pom.xml
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsFilter.java
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
pom.xml
testsuite/optional-tck/pom.xml
testsuite/optional-tck/src/test/java/io/smallrye/metrics/tck/optional/JaxRsMetricsActivatingProcessor.java
testsuite/optional-tck/src/test/java/io/smallrye/metrics/tck/optional/JaxRsMetricsExtension.java
testsuite/optional-tck/src/test/java/io/smallrye/metrics/tck/optional/MetricsHttpServlet.java
testsuite/optional-tck/src/test/resources/META-INF/jboss-deployment-structure.xml
testsuite/optional-tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
testsuite/optional-tck/src/test/resources/WEB-INF/jboss-web.xml
testsuite/optional-tck/src/test/resources/WEB-INF/web.xml
testsuite/pom.xml

Fixes https://github.com/smallrye/smallrye-metrics/issues/231

JAX-RS metrics support, using Servlet API + Update to MP Metrics 2.3 Final

---

implementation/src/main/java/io/smallrye/metrics/ExtendedMetadata.java
implementation/src/main/java/io/smallrye/metrics/ExtendedMetadataBuilder.java
implementation/src/test/java/io/smallrye/metrics/ExtendedMetadataBuilderTest.java

Signed-off-by: Miguel Serra <serramiguel1@gmail.com>

[#230] Implement a builder for ExtendedMetadata

---

implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/test/java/io/smallrye/metrics/exporters/OpenMetricsExporterTest.java

Fix escaping of newline characters

---

implementation/src/main/java/io/smallrye/metrics/MemberToMetricMappings.java
implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/MemberInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/RawMemberInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIMemberInfo.java
implementation/src/main/java/io/smallrye/metrics/interceptors/ConcurrentGaugeInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/GaugeRegistrationInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/MeteredInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/SimplyTimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/interceptors/TimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java

Fixes https://github.com/smallrye/smallrye-metrics/issues/260
Not to be merged yet, needs a bit more testing

Switch to using a map for matching methods to metrics

---

implementation/src/main/java/io/smallrye/metrics/MemberToMetricMappings.java
implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
implementation/src/test/java/io/smallrye/metrics/registration/RegistrationCornerCasesTest.java

Improve inferring of metric types

---

implementation/src/main/java/io/smallrye/metrics/elementdesc/RawMemberInfo.java

Coerce an empty parameterTypeNames array

---

implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsFilter.java
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
pom.xml

also fixes https://github.com/smallrye/smallrye-metrics/issues/317

Spec 3.0-M5

---

doc/antora-playbook.yml
doc/antora.yml
doc/modules/ROOT/nav.adoc
doc/modules/ROOT/pages/base-and-vendor-metrics.adoc
doc/modules/ROOT/pages/cdi-extension.adoc
doc/modules/ROOT/pages/extended-metadata.adoc
doc/modules/ROOT/pages/index.adoc
doc/modules/ROOT/pages/jaxrs-metrics.adoc
doc/modules/ROOT/pages/metric-registry-lifecycle.adoc

Mostly just a copy of 2.4 docs for now, to be improved later

Add initial docs for 3.0

---

api/pom.xml
api/src/main/java/io/smallrye/metrics/api/FunctionGaugeSupport.java
implementation/pom.xml
implementation/src/main/java/io/smallrye/metrics/MetricsRegistryImpl.java
pom.xml

First part of the fix needed for https://github.com/quarkusio/quarkus/issues/12196

Quarkus issue 12196

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java

Ability to turn off CORS headers

---

implementation/src/main/java/io/smallrye/metrics/MemberToMetricMappings.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricCdiInjectionExtension.java

Possible fix for #420 on 3.0.x

#420 Clean up metrics member to metric mappings on shutdown

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
README.adoc

Equivalent of https://github.com/smallrye/smallrye-metrics/pull/476 for the jakarta branch

Jakarta updates

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java

Requests without an Accept header are not accepted

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/AnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/RawAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/exporters/Exporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/GaugeRegistrationInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/setup/MPPrometheusMeterRegistry.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetadataMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java

Related to : https://github.com/eclipse/microprofile-metrics/pull/667 
Fixes #516 
Fixes #502 
Fixes #519
Fixes #520

Micrometer custom scopes + other fixes

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/AnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/RawAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/exporters/Exporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/GaugeRegistrationInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/setup/MPPrometheusMeterRegistry.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetadataMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java

Related to https://github.com/eclipse/microprofile-metrics/pull/699
Depends on :
FIRST: https://github.com/smallrye/smallrye-metrics/pull/513
(Current PR contains the commits of above )
Relevant commit is (or whatever the last commit is ):  https://github.com/smallrye/smallrye-metrics/pull/517/commits/aa0a78dfbca206a4225f0d215f773b2a3a3d1895

Micrometer gauge number

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java
implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/AnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/RawAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/elementdesc/adapter/cdi/CDIAnnotationInfo.java
implementation/src/main/java/io/smallrye/metrics/exporters/Exporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/OpenMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java
implementation/src/main/java/io/smallrye/metrics/jaxrs/JaxRsMetricsServletFilter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricsExtension.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/SnapshotAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/GaugeRegistrationInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/setup/MPPrometheusMeterRegistry.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
implementation/src/test/java/io/smallrye/metrics/MetricRegistryThreadSafetyTest.java
implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetadataMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
implementation/src/test/java/io/smallrye/metrics/registration/ReusabilityByDefaultTest.java

@jgallimore 
Forgot to make a PR for this one.
See last commit: 
e1b58eb10e355beaddc0451b16a1c58c0e5a9bf3
This fixes some issues for passing the API TCK.
It was too many branches deep at this point so decided to make a new branch!

Various fixes to pass MP Metrics API TCK

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/main/java/io/smallrye/metrics/exporters/PrometheusMetricsExporter.java

Check if metric exists in scope when querying across scopes

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java

Use correct var for outputting missing scope

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/base/LegacyBaseMetrics.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java

Throw IAE if mp_app or mp_scope is used as a tag, update with constants

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java
implementation/src/main/java/io/smallrye/metrics/OriginAndMetadata.java
implementation/src/main/java/io/smallrye/metrics/SmallRyeMetricsLogging.java
implementation/src/main/java/io/smallrye/metrics/SmallRyeMetricsMessages.java
implementation/src/main/java/io/smallrye/metrics/UnspecifiedMetadata.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/AnnotatedGaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/GaugeAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/LegacyMetricRegistryAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/MemberToMetricMappings.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/MeterHolder.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/MpMetadata.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/CountedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/GaugeRegistrationInterceptor.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/interceptors/TimedInterceptor.java
implementation/src/main/java/io/smallrye/metrics/setup/MetricsMetadata.java
implementation/src/test/java/io/smallrye/metrics/exporters/MpMetricsCompatibility_Programmatic_PrometheusTest.java
implementation/src/test/java/io/smallrye/metrics/registration/MetricTypeMismatchTest.java
pom.xml

This corresponds to the changes here: https://github.com/eclipse/microprofile-metrics/pull/740

Remove MetricType

---

implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java

Enable timer percentile precision to be configurable, with 3 as a default, which uses considerably less memory than 5.

Enable timer percentile precision to be configurable

---

implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java
pom.xml

- Producer to produce with RegistryType  Qualifier
**- temp: pom.xml to point to MP Metrics 5.0.0-RCR (<- Update to  5.0.0 (final) when avail for final PR)**
See: https://github.com/eclipse/microprofile-metrics/pull/748

[Draft] Producer to produce with RegistryType  Qualifier

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java

Micrometer  branch PR for 497
Also reintroduces the deleted `implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java` with changes to remove `application/json` expected results.

Requests without an Accept header are not accepted  - Micrometer Branch

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/main/java/io/smallrye/metrics/SharedMetricRegistries.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/CounterAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/HistogramAdapter.java
implementation/src/main/java/io/smallrye/metrics/legacyapi/TimerAdapter.java

fixes #567
Not sure why formatter plugin has changed.

Default to SimpleMeterRegistry when Prometheus is unavailable

---

.github/project.yml

Release 5.0.0-M5

---

implementation/src/main/java/io/smallrye/metrics/MetricProducer.java

add histogram  metricIds to cdi extension

---

implementation/src/main/java/io/smallrye/metrics/MetricsRequestHandler.java
implementation/src/test/java/io/smallrye/metrics/MediaHandlerTest.java

Trim accept header values

---

implementation/src/main/java/io/smallrye/metrics/MetricRegistryProducer.java

See: https://github.com/eclipse/microprofile-metrics/pull/778

Support @RegistryScope as a qualifer
